### ISSUE TITLE
WNNM wrapper

### ISSUE THREAD

**Issue by NSQY** [Irrational-Encoding-Wizardry/vs-denoise#42]
WNNM requires an additional, user-defined loop for effective noise reduction:
https://github.com/WolframRhodium/VapourSynth-WNNM#implementation

**Comment by Setsugennoao** [comment]
Simply will be done

**Comment by Setsugennoao** [comment]
Done something simple in https://github.com/Irrational-Encoding-Wizardry/vs-denoise/commit/f72a1b5b201034ea032115f0e54b0b163442e1bb
Reopen this issue if you want something else in it
