### ISSUE TITLE
Temporal Degrain (Request)

### ISSUE THREAD

**Issue by nobananasforyou** [Irrational-Encoding-Wizardry/vs-denoise#48]
Hello!

Hope you are doing well. I would like to thank you for all your hard work in bringing optimizations and features to vs. Could you please make Temporal Degrain process content in 16bit as the current port is limited to 8bit processing. There are other useful variants at the bottom of avs's wiki page such as the ChromaMod for grayscale sources http://avisynth.nl/index.php/Temporal_Degrain
You can find the vs port here: https://github.com/Irrational-Encoding-Wizardry/fvsfunc/blob/master/fvsfunc.py#L1166

Kind Regards

**Comment by Setsugennoao** [comment]
Hello, thanks!
Do you work on live action content?
I've always found FFT3D to create ghosting, and it's the main plugin used in this function, but I also mainly work on anime, and haven't extensively used it on IRL stuff. 🤔

**Comment by nobananasforyou** [comment]
No, I do not work on live action content. From my testing, it works really well with SD/DVD content and have not seen any ghosting on the anime sources I've tested it with.

**Comment by Setsugennoao** [comment]
Trumped by better detailed issue https://github.com/Irrational-Encoding-Wizardry/vs-denoise/issues/70
