### ISSUE TITLE
BM3Ds: Certain frame properties get removed

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/vs-denoise#77]
With BM3DCuda (and presumably, the core BM3D class in general), certain frame properties get removed at the end of the process. I've verified the same happens with DPIR (see https://github.com/Irrational-Encoding-Wizardry/lvsfunc/issues/158). I have not yet verified what the exact cause is, but a temporary workaround is to simply copy the props of the input clip to the output clip.

**Comment by LightArrowsEXE** [comment]
After talking about this with Setsu in [our PMs](https://discord.com/channels/@me/856164891098742804/1075820453257543691), we determined it's probably the RGB conversion. This should be double-checked in multiple functions and fixed if possible.

**Comment by adworacz** [comment]
Just a note - Full Range content is broken as well, even when setting the `range_in` parameter properly.

It looks like the BM3D functions don't carry through the input's range properly.
