### ISSUE TITLE
DFTTest does not respect user-specified sigma

### ISSUE THREAD

**Issue by shssoichiro** [Irrational-Encoding-Wizardry/vs-denoise#96]
For example, when calling `vsdenoise.DFTTest(clip).denoise(sigma=0.2)` (or just to be extra careful, `vsdenoise.DFTTest(clip, sigma=0.2).denoise(sigma=0.2)` also produces identical results), the video clip is filtered as if the default sigma of 8.0 is used. In most sane cases, this results in denoising that is stronger than expected.

[Slowpics comparison](https://slow.pics/c/bk772XJj)

Image 1: `dfttest2.DFTTest(clip, sigma=0.2, backend=dfttest2.Backend.CPU)`
Image 2: `vsdenoise.DFTTest(clip).denoise(sigma=0.2)`

The expectation is that these should be identical.

**Comment by Setsugennoao** [comment]
Are you on git latest?

**Comment by shssoichiro** [comment]
Yes, double checked that Windows doesn't have some double-installed python or something.
